---
chdir: /home/dumbstore/
rackup: /home/dumbstore/deploy/thin-config.ru
environment: production
address: 0.0.0.0
port: 8387
timeout: 30
log: log/thin.log
pid: tmp/pids/thin.pid
max_conns: 1024
max_persistent_conns: 100
require: []
wait: 30
servers: 4
daemonize: true